### PR TITLE
rtt_rosparam_tests: add unit tests for the new DataSource feature

### LINKED ISSUE #158: Broken operation callers for ROS param
After the commit d68265a2beb38724c32814b46243de9af39ebbb0 the following code:
    boost::shared_ptr<rtt_rosparam::ROSParam> rosparam = this->getProvider<rtt_rosparam::ROSParam>("rosparam");

 
generates errors:

0.000 [ ERROR  ][CollisionDetectorComponent::configureHook] Tried to construct OperationCaller from incompatible local operation.
0.000 [ ERROR  ][CollisionDetectorComponent::configureHook] Constructing RemoteOperationCaller for addRosParamPropertyEigenVectorXd was not possible.
0.000 [ ERROR  ][CollisionDetectorComponent::configureHook] Probable cause: Bad DataSource assignment: incompatible types.

etc.

### PR DESCRIPTION
**Pull request by spd-intermodalics**
# Description

This PR offers unit tests for the new `RosParamDataSource` from PR #148.

## Details

The unit test source related with `rtt_rosparam` in package `rtt_rosparam_tests` includes a new tests named `AddRosParamDataSources`. This particular test sets ROS parameters and creates properties using the new data source that link the evaluation and setting to the ROS parameter server.

* ROS paramters are read and checked from the unit test.
* ROS parameters are written out and check from the unit test.

## PR management

This PR makes the PR #150 obsolete. This new PR cherry-pics the contribution of PR #150 and then removes the code related with the closed PR #147.

Fixes https://github.com/orocos/rtt_ros_integration/issues/158.

### CODE REVIEW

File: tests/rtt_rosparam_tests/test/param_tests.cpp [hunk 1]
```diff
@@ -606,6 +642,49 @@ TEST_F(ParamTest, SetValueOnParameterServer)
...
+  // change the props values to an alternative configuration
+  props.initialize_alternative();
+
+  // Write out paramters through data source
+  bool in_bool;
+  double in_double;
+  float in_float;
+  int in_int;
+  std::string in_string;
+  dynamic_cast<RTT::Property<bool>*>(tc->getProperty("bool_parameter"))->set(props.bool_);
```
Comment (meyerj) [inline tests/rtt_rosparam_tests/test/param_tests.cpp]: nit: There is a special member function [RTT::PropertyBag::getPropertyType\<T>(name)](https://orocos-toolchain.github.io/rtt/toolchain-2.9/api/html/classRTT_1_1PropertyBag.html#a5d2825978bc3fee037bf39abc4f4648f) that includes the cast, but it is not exposed in `RTT::TaskContext` directly:

```suggestion
  tc->properties()->getPropertyType<bool>("bool_parameter")->set(props.bool_);
```
Whatever you prefer.

**Review by meyerj — APPROVED** [review]
LGTM. This patch also fixes https://github.com/orocos/rtt_ros_integration/issues/158.
